Support 7503 and other changes; Closes #32
Teledyne-Marine/pyread7k pull request #34
Opened 2022-04-08 12:23 UTC by rogvidarge

This pull request adds support for record 7503. It also streamlined the setup of a development setup and cleaned up the test environment.

2022-04-08 13:35 UTC, rasmus-klett-tele commented on pyread7k/records.py
> +    """ The tilt of the sonar around the y axis (in the vessels coordinate system) """
Ooops

2022-04-08 13:40 UTC, rasmus-klett-tele commented on pyread7k/records.py
> +    xx_series_altnernate_gain: float
Misspelled "projector" and "alternate"

2022-04-20 14:49 UTC, rogvidarge commented on pyread7k/records.py
> +    xx_series_altnernate_gain: float
Fixed

2022-04-21 09:43 UTC, rasmus-klett-tele requested changes

2022-04-21 09:43 UTC, rasmus-klett-tele commented on pyread7k/_datarecord.py
> +        ("xx_series_altnernate_gain", elemT.f32),
"projector" and "alternate" are still misspelled here, which causes an error in tests since they are now fixed on the record definition.

2022-04-21 10:20 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
That's strange. I can't get it to accept it as a one-liner even when removing the trailing commas.

2022-04-21 10:20 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
Nevermind. I missed one. I've updated it.

2022-04-21 10:22 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +        ("xx_series_altnernate_gain", elemT.f32),
True. I've fixed this.

2022-04-21 10:27 UTC, rasmus-klett-tele commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
Is this a bug in Black? I thought it was supposed to not be influenced by the original formatting

2022-04-21 10:28 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +            self._block_rth = _record_data_block(self._fields, source_rth_size)
True, I wasn't thinking of the reading in the context of the reader, but in the context of the dataset only. It makes sense to make a local datablock in the reading. I've modified the code and will check in after running tests.

2022-04-21 10:30 UTC, rasmus-klett-tele commented on pyread7k/_datarecord.py
> +            self._block_rth = _record_data_block(self._fields, source_rth_size)
Cool. I think it's yet another design flaw of the current reader code that this is even something we have to think about, unfortunately.

2022-04-21 10:32 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
Good question, that I don't have an answer to. It might be a case where both formats are valid.

2022-04-21 10:36 UTC, rogvidarge commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
Check the documentation on trailing commas and single element tuple expressions: https://test-black.readthedocs.io/en/style-guide/the_black_code_style.html

2022-04-21 10:40 UTC, rasmus-klett-tele commented on pyread7k/_datarecord.py
> +        _bytes_to_str(
> Black reformats entire files in place. It is not configurable. It doesn’t take previous formatting into account.
> ...
> Unnecessary trailing commas are removed if an expression fits in one line. 

I found these lines in the docs. To me, this reads like Black should output the single-line formatting of this code regardless of whether we put trailing commas. So this does look like a Black bug right?

2022-04-21 14:07 UTC, rasmus-klett-tele commented
I've changed the Sphinx config to show the top-level exports. If you agree with that change, I will merge :)

2022-04-21 14:58 UTC, merged