Added support for 7044; closes #37
Teledyne-Marine/pyread7k pull request #38
Opened 2022-05-31 13:43 UTC by rogvidarge

Added support for record 7044, which is a record containing only beamformed magnitude data

2022-06-02 13:47 UTC, rasmus-klett-tele requested changes
Some minor changes needed before merging :)

2022-06-02 13:47 UTC, rasmus-klett-tele commented on pyread7k/records.py
> +    record_type: int = field(default=7018, init=False)
Copy-paste error, should be 7044 :)

2022-06-02 13:47 UTC, rasmus-klett-tele commented on pyread7k/records.py
> +    Contains the beamformed magnitude.
I would like the docstring to have a "Draft definition!" warning like record 7038, since it is subject to change until it is published in an official DFD version.

2022-06-03 11:36 UTC, rogvidarge commented on pyread7k/records.py
> +    record_type: int = field(default=7018, init=False)
True. Fixing

2022-06-03 11:39 UTC, rogvidarge commented on pyread7k/records.py
> +    Contains the beamformed magnitude.
Fixed

2022-06-03 11:39 UTC, rogvidarge commented on pyread7k/records.py
> +    flags: int
Sounds like a fine idea.

2022-06-03 11:40 UTC, rogvidarge commented on pyread7k/records.py
> +    flags: int
For 7044, there are currently no descriptions other than it is reserved for future use, so I will only add the underscore and nothing more here.

2022-06-07 07:48 UTC, rasmus-klett-tele requested changes

2022-06-07 07:48 UTC, rasmus-klett-tele commented on pyproject.toml
> +black = "^20.8b1"
This is a quite old version of Black. I think we should just use 22.3, it has been out for several months.

2022-06-07 07:48 UTC, rasmus-klett-tele commented on pyproject.toml
> +version = "2.1.1"
I know I asked you previously to bump versions, but now that I know the process I think it's better if I do it. That way I can synchronize it with actually publishing new versions to pypi :)

2022-06-07 07:48 UTC, rasmus-klett-tele commented on pyproject.toml
> +version = "2.1.1"
We really should start a changelog soon though, so that I can know whether a version bump should be major or minor :)

2022-06-13 12:57 UTC, rogvidarge commented on pyproject.toml
> +black = "^20.8b1"
Done

2022-06-13 12:57 UTC, rogvidarge commented on pyproject.toml
> +version = "2.1.1"
Downgraded to 2.1.0

2022-06-13 12:59 UTC, merged